server:
  port: 8011

spring:
  application:
    name: ping-service
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: earliest
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.hsbc.pingpong.common.event"
        spring.json.value.default.type: "com.hsbc.pingpong.common.event.PingPongEvent"
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:pingpong}
    username: ${POSTGRES_USER:appuser}
    password: ${POSTGRES_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

hsbc:
  pingpong:
    instance-id: ${PING_INSTANCE_ID:ping-${server.port:8011}}
    pong-url: ${PONG_URL:http://localhost:8033}
    rate-limit:
#      type: redis-lua
      type: file-lock
      max-tokens: 2
      refill-per-second: 2
      step: 1
      key: ping-pong-rate-limit
      lock-file: ./ping-pong-events.lock
    kafka:
      enabled: true
      topic: ping-pong-events
      group-id: ping-service
      max-retries: 3
      retry-backoff-ms: 1000
      dlt-topic: ping-pong-events-dlt

logging:
  level:
    com.hsbc.pingpong: INFO
