apiVersion: v1
kind: Service
metadata:
  name: pong-service
  namespace: pingpong
spec:
  selector:
    app: pong-service
  ports:
    - port: 8033
      targetPort: 8033
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-service
  namespace: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong-service
  template:
    metadata:
      labels:
        app: pong-service
    spec:
      containers:
        - name: pong-service
          image: pong-service:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8033
          env:
            - name: SERVER_PORT
              value: "8033"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: pingpong
            - name: POSTGRES_USER
              value: appuser
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
            - name: PING_INSTANCE_ID
              value: pong-1
          readinessProbe:
            tcpSocket:
              port: 8033
            initialDelaySeconds: 15
            periodSeconds: 5
